<?php

namespace Juzaweb\MultipleStorage\Repositories;

use Juzaweb\CMS\Repositories\BaseRepositoryEloquent;
use Juzaweb\CMS\Repositories\Criterias\SortCriteria;
use Juzaweb\CMS\Traits\Criterias\UseFilterCriteria;
use Juzaweb\CMS\Traits\Criterias\UseSearchCriteria;
use Juzaweb\CMS\Traits\Criterias\UseSortableCriteria;
use Juzaweb\MultipleStorage\Models\Storage;

class StorageRepositoryEloquent extends BaseRepositoryEloquent implements StorageRepository
{
    use UseSearchCriteria, UseFilterCriteria, UseSortableCriteria;

    protected array $searchableFields = [
        'name',
    ];

    protected array $filterableFields = [
        'type',
        'created_at',
    ];

    protected array $sortableFields = [
        'id',
        'created_at',
    ];

    protected array $sortableDefaults = ['created_at' => 'desc'];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $this->pushCriteria(SortCriteria::class);
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model(): string
    {
        return Storage::class;
    }
}
